# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: apavlovs <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/07 15:27:32 by apavlovs          #+#    #+#              #
#    Updated: 2018/11/07 15:34:55 by apavlovs         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_display_file
SOURCES=sources/*.c

all:
	gcc $(SOURCES) -o $(NAME)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)

re: fclean re
